SECRET_KEY_BASE: 401b84dc313e07702ab3216a9ac880b56f580b8bf465e262d41efc9b97c922300a681abc961d66f9dc1e5da1cfbe7692f68e3ea00064e343b3c0c7e65e2e506a
AWS_ACCES_KEY_ID: AKIAI5HVWHOQDD42723A
AWS_SECRET_ACCESS_KEY: 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
AWS_REGION: us-east-1
EMAIL_LOGIN: chineduabalogu@gmail.com
EMAIL_PASSWORD: STTwzgG5hHGo3d3vsG4IKw

development:
  S3_BUCKET_NAME: lydiasblog-dev
production:
  S3_BUCKET_NAME: lydiasblog-prod